spring.application.name=room_rental_application

## H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:roomrentaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

## Server Configuration
server.port=8000


spring.security.user.name=admin
spring.security.user.password=123

## logging configuration
logging.level.root=info

## Jwt configuration
spring.profiles.include=local
jwt.secret=${JWT_SECRET}
access.token.expiration = ${ACCESS_TOKEN_EXPIRATION}
refresh.token.expiration = ${REFRESH_TOKEN_EXPIRATION}


## SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

